version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
     
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend

    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
