version: '3.8'

networks:
  dev:

services:
  backend:
    build: ./backend
    env_file:
      - .env
    networks:
      - dev

  
  frontend:
    build: ./frontend
    env_file: .env
    networks:
      - dev
  
  nginx:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - dev
