version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
     
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      # Конфиг nginx (прокси /api → backend)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # SSL
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend

    networks:
      - dev

